### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by fontani** [salesforce-ux/design-system#208]
Hi all. Was trying to install this in my pc (windows 7 64). and the npm start is failing. checked npm version: 2.14.4, node is 4.1.1. cleaned cache and tried several times without luck, here is the log I got, I am a designer so not much of a clue here, let me know if I am missing something thanks

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart design-system@1.0.2
6 info start design-system@1.0.2
7 verbose unsafe-perm in lifecycle true
8 info design-system@1.0.2 Failed to exec start script
9 verbose stack Error: design-system@1.0.2 start: `npm run gulp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid design-system@1.0.2
11 verbose cwd C:\Users\maq 2\OneDrive- TWG\UXUI\designmaster
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.1.1
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error design-system@1.0.2 start: `npm run gulp`
17 error Exit status 1
18 error Failed at the design-system@1.0.2 start script 'npm run gulp'.
18 error This is most likely a problem with the design-system package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run gulp
18 error You can get their info via:
18 error     npm owner ls design-system
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by kaelig** [comment]
Thank you @fontani for reporting this. It looks like it might be a Windows/npm related issue. I suggest that you try running the command `gulp` directly instead of using the npm task runner, and then let us know if that worked for you. Thanks again!

**Comment by fontani** [comment]
thanks @kaelig  did what you suggested: run gulp without hte npm and got an error when generating ui, check below, what do you think?

C:\Users\maq 2\OneDrive- TWG\UXUI\designmaster>gulp
[08:50:11] Using gulpfile ~\OneDrive- TWG\UXUI\designmaster\gulpfile.js
[08:50:11] Starting 'default'...
[08:50:11] Starting 'clean'...
[08:50:46] Finished 'clean' after 34 s
[08:50:46] Starting 'styles'...
[08:50:49] Finished 'styles' after 3.29 s
[08:50:49] Starting 'assets:icons'...
[08:50:49] Starting 'assets:icons:zip'...
[08:50:49] Starting 'generate:icons'...
[08:50:49] Starting 'generate:release-notes'...
[08:50:49] Starting 'generate:tokens:zip:ios'...
[08:50:49] Starting 'generate:tokens:zip:android'...
[08:50:49] Starting 'generate:tokens:zip:styl'...
[08:50:49] Starting 'generate:tokens:zip:less'...
[08:50:49] Starting 'generate:tokens:zip:scss'...
[08:50:49] Starting 'generate:tokens'...
[08:50:49] Starting 'generate:ui'...
[08:50:49] 'generate:ui' errored after 25 ms
[08:50:49] Error: ENOENT: no such file or directory, open 'C:\components\activit
y-timeline\flavors\base\config.yml'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.getConfig (index.js:37:37)
    at Array.map (native)
    at Object.getFlavors (index.js:69:10)
    at index.js:60:27
    at Array.map (native)
    at Object.getComponents (index.js:53:10)
    at index.js:30:30
    at Array.map (native)
    at Object.generate (index.js:25:10)
    at generateUI (generate-ui.js:45:53)
    at Gulp.<anonymous> (generate-ui.js:53:29)
    at module.exports (C:\Users\maq 2\OneDrive- TWG\UXUI\designmaster\node_modul
es\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\maq 2\OneDrive- TWG\UXUI\designmaste
r\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
[08:50:49] 'default' errored after 38 s
[08:50:49] Error in plugin 'run-sequence'
Message:
    An error occured in task 'generate:ui'.
[08:50:50] Finished 'generate:release-notes' after 767 ms
[08:50:50] Finished 'assets:icons:zip' after 784 ms
[08:50:50] Finished 'generate:tokens' after 848 ms
[08:50:50] Finished 'generate:tokens:zip:android' after 961 ms
[08:50:50] Finished 'generate:tokens:zip:ios' after 965 ms
[08:50:50] Finished 'generate:tokens:zip:less' after 960 ms
[08:50:50] Finished 'generate:tokens:zip:styl' after 964 ms
[08:50:50] Finished 'generate:tokens:zip:scss' after 1.08 s
[08:50:51] Finished 'generate:icons' after 1.58 s
[08:50:52] Finished 'assets:icons' after 3.42 s

**Comment by kaelig** [comment]
Thank you for the report. There was an issue in 1.0.2, sorry for the inconvenience. Could you please try with the new version 1.0.3 and let us know how it goes?

**Comment by fontani** [comment]
no luck yet. I tried 1.0.3 and it went like this: npm start gave me the same error than the first time. so I did the gulp thing without the npm and got this error:

C:\Users\maq 2\OneDrive- TWG\UXUI\designmaster>gulp
[08:50:11] Using gulpfile ~\OneDrive- TWG\UXUI\designmaster\gulpfile.js
[08:50:11] Starting 'default'...
[08:50:11] Starting 'clean'...
[08:50:46] Finished 'clean' after 34 s
[08:50:46] Starting 'styles'...
[08:50:49] Finished 'styles' after 3.29 s
[08:50:49] Starting 'assets:icons'...
[08:50:49] Starting 'assets:icons:zip'...
[08:50:49] Starting 'generate:icons'...
[08:50:49] Starting 'generate:release-notes'...
[08:50:49] Starting 'generate:tokens:zip:ios'...
[08:50:49] Starting 'generate:tokens:zip:android'...
[08:50:49] Starting 'generate:tokens:zip:styl'...
[08:50:49] Starting 'generate:tokens:zip:less'...
[08:50:49] Starting 'generate:tokens:zip:scss'...
[08:50:49] Starting 'generate:tokens'...
[08:50:49] Starting 'generate:ui'...
[08:50:49] 'generate:ui' errored after 25 ms
[08:50:49] Error: ENOENT: no such file or directory, open 'C:\components\activit
y-timeline\flavors\base\config.yml'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.getConfig (index.js:37:37)
    at Array.map (native)
    at Object.getFlavors (index.js:69:10)
    at index.js:60:27
    at Array.map (native)
    at Object.getComponents (index.js:53:10)
    at index.js:30:30
    at Array.map (native)
    at Object.generate (index.js:25:10)
    at generateUI (generate-ui.js:45:53)
    at Gulp.<anonymous> (generate-ui.js:53:29)
    at module.exports (C:\Users\maq 2\OneDrive- TWG\UXUI\designmaster\node_modul
es\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\maq 2\OneDrive- TWG\UXUI\designmaste
r\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
[08:50:49] 'default' errored after 38 s
[08:50:49] Error in plugin 'run-sequence'
Message:
    An error occured in task 'generate:ui'.
[08:50:50] Finished 'generate:release-notes' after 767 ms
[08:50:50] Finished 'assets:icons:zip' after 784 ms
[08:50:50] Finished 'generate:tokens' after 848 ms
[08:50:50] Finished 'generate:tokens:zip:android' after 961 ms
[08:50:50] Finished 'generate:tokens:zip:ios' after 965 ms
[08:50:50] Finished 'generate:tokens:zip:less' after 960 ms
[08:50:50] Finished 'generate:tokens:zip:styl' after 964 ms
[08:50:50] Finished 'generate:tokens:zip:scss' after 1.08 s
[08:50:51] Finished 'generate:icons' after 1.58 s
[08:50:52] Finished 'assets:icons' after 3.42 s

then I just wanted to check if this is a blocker when serving the slds. so I did gulp serve

and got the localhost url but the page says "cannot GET"

and the error in the console is this:

C:\Users\maq 2\OneDrive- TWG\UXUI\designmaster>gulp
[08:50:11] Using gulpfile ~\OneDrive- TWG\UXUI\designmaster\gulpfile.js
[08:50:11] Starting 'default'...
[08:50:11] Starting 'clean'...
[08:50:46] Finished 'clean' after 34 s
[08:50:46] Starting 'styles'...
[08:50:49] Finished 'styles' after 3.29 s
[08:50:49] Starting 'assets:icons'...
[08:50:49] Starting 'assets:icons:zip'...
[08:50:49] Starting 'generate:icons'...
[08:50:49] Starting 'generate:release-notes'...
[08:50:49] Starting 'generate:tokens:zip:ios'...
[08:50:49] Starting 'generate:tokens:zip:android'...
[08:50:49] Starting 'generate:tokens:zip:styl'...
[08:50:49] Starting 'generate:tokens:zip:less'...
[08:50:49] Starting 'generate:tokens:zip:scss'...
[08:50:49] Starting 'generate:tokens'...
[08:50:49] Starting 'generate:ui'...
[08:50:49] 'generate:ui' errored after 25 ms
[08:50:49] Error: ENOENT: no such file or directory, open 'C:\components\activit
y-timeline\flavors\base\config.yml'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.getConfig (index.js:37:37)
    at Array.map (native)
    at Object.getFlavors (index.js:69:10)
    at index.js:60:27
    at Array.map (native)
    at Object.getComponents (index.js:53:10)
    at index.js:30:30
    at Array.map (native)
    at Object.generate (index.js:25:10)
    at generateUI (generate-ui.js:45:53)
    at Gulp.<anonymous> (generate-ui.js:53:29)
    at module.exports (C:\Users\maq 2\OneDrive- TWG\UXUI\designmaster\node_modul
es\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\maq 2\OneDrive- TWG\UXUI\designmaste
r\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
[08:50:49] 'default' errored after 38 s
[08:50:49] Error in plugin 'run-sequence'
Message:
    An error occured in task 'generate:ui'.
[08:50:50] Finished 'generate:release-notes' after 767 ms
[08:50:50] Finished 'assets:icons:zip' after 784 ms
[08:50:50] Finished 'generate:tokens' after 848 ms
[08:50:50] Finished 'generate:tokens:zip:android' after 961 ms
[08:50:50] Finished 'generate:tokens:zip:ios' after 965 ms
[08:50:50] Finished 'generate:tokens:zip:less' after 960 ms
[08:50:50] Finished 'generate:tokens:zip:styl' after 964 ms
[08:50:50] Finished 'generate:tokens:zip:scss' after 1.08 s
[08:50:51] Finished 'generate:icons' after 1.58 s
[08:50:52] Finished 'assets:icons' after 3.42 s


thanks for looking into this, let me know if there is anything I could do

**Comment by kaelig** [comment]
Thank you for trying! I'll look further into it.

**Comment by kaelig** [comment]
I was able to reproduce the issue. 

@aputinski looks like the `getFlavors` function tries to fetch the config files at the root (`C:\components\activit
y-timeline\flavors\base\config.yml`) instead of a relative path. Can you have a look?

**Comment by aputinski** [comment]
Thanks for finding the problem! Shouldn't be too hard to fix.

**Comment by fontani** [comment]
is there any update on this one? let me know please thank you

**Comment by aputinski** [comment]
@fontani I apologize for the delay. I will try to get to this as soon as possible.

**Comment by fontani** [comment]
Hi @aputinski is there anything I can do to help? let me know :D

**Comment by kaelig** [comment]
Thanks for following up and for your patience, @fontani! @aputinski has fixed it in our internal branch. We will release a public patch very soon. Watch this space!

**Comment by fontani** [comment]
excelent!

2016-05-17 13:59 GMT-03:00 Kaelig <notifications@github.com>:

**Comment by kaelig** [comment]
@fontani thanks again for your patience. This should now be fixed in the new 1.0.4. Let us know how this goes for you!

**Comment by fontani** [comment]
¡Hola!

Acabo de firmar la petición "diputadofespinoza@gmail.com: Reclamamos y
pedimos ayuda para la rehabilitación de Wolfie" y me gustaría que te
sumaras a ella.

Nuestro objetivo es conseguir 2,500 firmas y necesitamos más personas que
la apoyen. Podés tener más información sobre la misma y firmarla acá:

http://chng.it/rFKss8PxwF

¡Muchas gracias!
Leonardo
