### ISSUE TITLE
Cannot npm install on windows

### ISSUE THREAD

**Issue by GusjkoA** [salesforce-ux/design-system#275]
Hi,
I've cloned the repo, and ran npm install

Ran into installation failed error:

```
982 warn optional Skipping failed optional dependency /chokidar/fsevents:
983 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.13
984 warn optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
985 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.13
986 warn autocomplete.js@0.17.3 requires a peer of angular@~1.4.2 but none was installed.
987 warn autocomplete.js@0.17.3 requires a peer of jquery@>= 1.7 but none was installed.
988 verbose stack Error: npm-zepto@1.1.7 install: `script/build`
988 verbose stack Exit status 1
988 verbose stack     at EventEmitter.<anonymous> (C:\NodeJs\Nodist\bin\node_modules\npm\lib\utils\lifecycle.js:242:16)
988 verbose stack     at emitTwo (events.js:106:13)
988 verbose stack     at EventEmitter.emit (events.js:191:7)
988 verbose stack     at ChildProcess.<anonymous> (C:\NodeJs\Nodist\bin\node_modules\npm\lib\utils\spawn.js:40:14)
988 verbose stack     at emitTwo (events.js:106:13)
988 verbose stack     at ChildProcess.emit (events.js:191:7)
988 verbose stack     at maybeClose (internal/child_process.js:852:16)
988 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
989 verbose pkgid npm-zepto@1.1.7
990 verbose cwd D:\Projects\SLDS
991 error Windows_NT 6.3.9600
992 error argv "C:\\NodeJs\\Nodist\\v-x64\\nodev6.3.0\\node.exe" "c:\\NodeJs\\Nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install"
993 error node v6.3.0
994 error npm  v3.10.5
995 error code ELIFECYCLE
996 error npm-zepto@1.1.7 install: `script/build`
996 error Exit status 1
997 error Failed at the npm-zepto@1.1.7 install script 'script/build'.
997 error Make sure you have the latest version of node.js and npm installed.
997 error If you do, this is most likely a problem with the npm-zepto package,
997 error not with npm itself.
997 error Tell the author that this fails on your system:
997 error     script/build
997 error You can get information on how to open an issue for this project with:
997 error     npm bugs npm-zepto
997 error Or if that isn't available, you can get their info via:
997 error     npm owner ls npm-zepto
997 error There is likely additional logging output above.
998 verbose exit [ 1, true ]
```

full log: [npm-debug.log.txt](https://github.com/salesforce-ux/design-system/files/365838/npm-debug.log.txt)

node and npm are of latest version. Running on Windows 8. Any ideas what could go wrong?

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System, @GusjkoA 

This is an issue we are aware of and will publish a fix for very shortly. Thank you for your patience!

**Comment by kaelig** [comment]
According to our latest tests, the design system now installs correctly on Windows as of SLDS v2.0.3. Thanks again for reporting this!

Feel free to reopen if this is still an issue.
