### ISSUE TITLE
SyntaxError: Invalid regular expression: /\/: \ at end of pattern

### ISSUE THREAD

**Issue by kevlangdo** [salesforce-ux/design-system#523]
I have node 9.1.0, npm 5.1.1 installed

output from Powershell on Windows 10
SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at chunked (C:/Users/klanguedoc/nodedev/design-system/scripts/compile/bundle.js:32:42)
    at entryMap.map (C:/Users/klanguedoc/nodedev/design-system/scripts/compile/bundle.js:46:35)
    at C:\Users\klanguedoc\nodedev\design-system\node_modules\immutable\dist\immutable.js:3018:46
    at C:\Users\klanguedoc\nodedev\design-system\node_modules\immutable\dist\immutable.js:1379:16
    at ArrayMapNode.iterate.HashCollisionNode.iterate [as iterate] (C:\Users\klanguedoc\nodedev\design-system\node_modules\immutable\dist\immutable.js:1728:11)
    at Map.__iterate (C:\Users\klanguedoc\nodedev\design-system\node_modules\immutable\dist\immutable.js:1377:32)
    at KeyedIterable.mappedSequence.__iterateUncached (C:\Users\klanguedoc\nodedev\design-system\node_modules\immutable\dist\immutable.js:3017:23)
    at seqIterate (C:\Users\klanguedoc\nodedev\design-system\node_modules\immutable\dist\immutable.js:606:16)
    at KeyedIterable.Seq.__iterate (C:\Users\klanguedoc\nodedev\design-system\node_modules\immutable\dist\immutable.js:276:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.4.5 previewer: `babel-node scripts/previewer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.4.5 previewer script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\klanguedoc\AppData\Roaming\npm-cache\_logs\2017-12-14T14_39_20_960Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.4.5 start: `npm run build && npm run previewer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.4.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\klanguedoc\AppData\Roaming\npm-cache\_logs\2017-12-14T14_39_21_012Z-debug.log

[SLDS Error Log 2017-11-16T19_07_07_616Z-debug.log](https://github.com/salesforce-ux/design-system/files/1559617/SLDS.Error.Log.2017-11-16T19_07_07_616Z-debug.log)

**Comment by engai** [comment]
@kevlangdo sorry to hear that you're experiencing this issue. I can't currently reproduce the issue on my end, but will look further into the issue.

cc: @DrBoolean @aputinski

**Comment by sunhaolin** [comment]
+1

**Comment by windofelm** [comment]
+1

**Comment by glefave** [comment]
Trying to install into Windows 10 Home  64bit.

To get the install to work I had to change the version number in package.js  to 4.7.2  then the install completed.
But when I try to run the previewer I get the same message regarding invalid regular expression.

I install the package as a clone so I think that is latest version, and reinstalled node.js to latest version.

Thanks for any help


C:\design-system>npm run previewer

> design-system@2.5.0 previewer C:\design-system
> babel-node scripts/previewer

Start compiling JS library for Previewer...
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the late
st available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https:
//fb.me/prop-types-docs
C:\design-system\scripts\compile\bundle.js:28
.setIn(["output", "jsonpFunction"], `webpackJsonpSLDS_${prefix.replace(new RegExp(path.sep, "g"), "_")}`).set("plugins",
 I.List.of(new webpack.optimize.CommonsChunkPlugin({
                                                                       ^

SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at chunked (C:/design-system/scripts/compile/bundle.js:32:42)
    at entryMap.map (C:/design-system/scripts/compile/bundle.js:46:35)
    at C:\design-system\node_modules\immutable\dist\immutable.js:3018:46
    at C:\design-system\node_modules\immutable\dist\immutable.js:1379:16
    at ArrayMapNode.iterate.HashCollisionNode.iterate [as iterate] (C:\design-system\node_modules\immutable\dist\immutab
le.js:1728:11)
    at Map.__iterate (C:\design-system\node_modules\immutable\dist\immutable.js:1377:32)
    at KeyedIterable.mappedSequence.__iterateUncached (C:\design-system\node_modules\immutable\dist\immutable.js:3017:23
)
    at seqIterate (C:\design-system\node_modules\immutable\dist\immutable.js:606:16)
    at KeyedIterable.Seq.__iterate (C:\design-system\node_modules\immutable\dist\immutable.js:276:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.5.0 previewer: `babel-node scripts/previewer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.5.0 previewer script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gene\AppData\Roaming\npm-cache\_logs\2018-01-26T16_13_16_255Z-debug.log

**Comment by glefave** [comment]
That was the node-sass package number that was incorrect.

**Comment by Tea56** [comment]
+1

**Comment by engai** [comment]
This bug has been resolved with https://github.com/salesforce-ux/design-system/commit/a990048ab292a0cf29f1c61af0c8785fa22a06e2 

Thank you again for bringing this to our attention.
