### ISSUE TITLE
Cannot Run Dist for Windows

### ISSUE THREAD

**Issue by moshner** [salesforce-ux/design-system#589]
Hello, I'm trying to run the `npm run build && npm run dist` command on Windows 10 and getting the following error:
`
(undefined) __internal\chunked\docs\ui\components\cards\docs.mdx.js from UglifyJs
Invalid hex-character pattern in string [__internal\chunked\docs\ui\components\cards\docs.mdx.js:1,28]
    at webpack.run (C:/Code/git/UI/slds-assets-sync/scripts/compile/bundle.js:104:11)
    at runWithDependencies.err (C:\Code\git\UI\slds-assets-sync\node_modules\webpack\lib\MultiCompiler.js:247:6)
    at done (C:\Code\git\UI\slds-assets-sync\node_modules\neo-async\async.js:2920:13)
    at runCompilers (C:\Code\git\UI\slds-assets-sync\node_modules\webpack\lib\MultiCompiler.js:171:48)
    at err (C:\Code\git\UI\slds-assets-sync\node_modules\webpack\lib\MultiCompiler.js:178:7)
    at compiler.run (C:\Code\git\UI\slds-assets-sync\node_modules\webpack\lib\MultiCompiler.js:242:7)
    at hooks.done.callAsync.err (C:\Code\git\UI\slds-assets-sync\node_modules\webpack\lib\Compiler.js:185:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Code\git\UI\slds-assets-sync\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Code\git\UI\slds-assets-sync\node_modules\tapable\lib\Hook.js:35:21)
    at emitRecords.err (C:\Code\git\UI\slds-assets-sync\node_modules\webpack\lib\Compiler.js:183:22)
    at Compiler.emitRecords (C:\Code\git\UI\slds-assets-sync\node_modules\webpack\lib\Compiler.js:295:39)
    at emitAssets.err (C:\Code\git\UI\slds-assets-sync\node_modules\webpack\lib\Compiler.js:177:10)
    at hooks.afterEmit.callAsync.err (C:\Code\git\UI\slds-assets-sync\node_modules\webpack\lib\Compiler.js:281:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Code\git\UI\slds-assets-sync\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Code\git\UI\slds-assets-sync\node_modules\tapable\lib\Hook.js:35:21)
    at asyncLib.forEach.err (C:\Code\git\UI\slds-assets-sync\node_modules\webpack\lib\Compiler.js:278:27)
[13:25:42] 'dist' errored after 1.52 min
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.7.4 gulp: `babel-node ./node_modules/gulp/bin/gulp.js "dist"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.7.4 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

I'm running node 8.11.2 and npm 6.4.1

**Comment by moshner** [comment]
[2018-11-13T19_25_42_529Z-debug.log](https://github.com/salesforce-ux/design-system/files/2577728/2018-11-13T19_25_42_529Z-debug.log)

**Comment by moshner** [comment]
We would still like to be able to run the DIST on windows.

**Comment by moshner** [comment]
Is anyone interested in looking at this?

**Comment by limuxy** [comment]
same problem here, dist works on linux, but fails on windows with error:
UglifyJS
Invalid hex-character pattern in string

**Comment by datamike** [comment]
On Windows 10 and I'm running node 10.16.3 and npm 6.9.0.

When I ran 'npm install':

"error cb() never called!
error This is an error with npm itself. Please report this error at: <https://npm.community>"

When I ran 'npm start':

```
> design-system@2.10.0 start c:\Code_Projects\Nodejs\LightningDesignSystem\design-system
> npm run build && npm run previewer

> design-system@2.10.0 build c:\Code_Projects\Nodejs\LightningDesignSystem\design-system
> npm run gulp -- build

> design-system@2.10.0 gulp c:\Code_Projects\Nodejs\LightningDesignSystem\design-system
> babel-node ./node_modules/gulp/bin/gulp.js "build"

'babel-node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.10.0 gulp: `babel-node ./node_modules/gulp/bin/gulp.js "build"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.10.0 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.10.0 build: `npm run gulp -- build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.10.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.10.0 start: `npm run build && npm run previewer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@2.10.0 start script.
```

I will try installing babel-node.

**Comment by moshner** [comment]
Please don't go stale.

**Comment by moshner** [comment]
Can someone from Salesforce please review this ticket? It keeps going stale because nobody is reviewing it.

**Comment by kirupa** [comment]
Hi @moshner - thanks for raising this. I'll chat with the team and see what we can do here.

**Comment by natxoski** [comment]
Hey @moshner, @kirupa

I have looked into this but in the following issue: 
https://github.com/salesforce-ux/design-system/issues/659

Not great but narrowed the problem down. I think I found some sort of workaround ( again not great, would be better to have a proper fix... )

Hope it helps!

**Comment by natxoski** [comment]
Please refer to #659 for the fix

**Comment by moshner** [comment]
The solutions on #659 are working for me. Thank you.

**Comment by Dottenpixel** [comment]
Closing as v2.14.3 is in with a fix
