### ISSUE TITLE
Unable to build, even with a fresh clone

### ISSUE THREAD

**Issue by Luke1982** [salesforce-ux/design-system#606]
I keep being unable to build on Ubuntu 18.04 running KDE Plasma. I've even cloned a completely fresh version of this repo. NPM and Node are both up to date and well above the required minimum versions.

No node hero so I was hoping someone here could give me some tips.

[12:04:17] 'dist:writeUtilityDeclarationsMap' errored after 57 ms
" (3:0)17] Error: Can't handle character: "
    at InputStream.err (/home/guido/gitrepos/LDS/node_modules/@salesforce-ux/scss-parser-aura/node_modules/scss-parser/dist/input-stream.js:122:13)
    at Object.err (/home/guido/gitrepos/LDS/node_modules/@salesforce-ux/scss-parser-aura/node_modules/scss-parser/dist/input-stream.js:161:20)
    at TokenStream.err (/home/guido/gitrepos/LDS/node_modules/@salesforce-ux/scss-parser-aura/node_modules/scss-parser/dist/token-stream.js:297:40)
    at TokenStream.read_next (/home/guido/gitrepos/LDS/node_modules/@salesforce-ux/scss-parser-aura/node_modules/scss-parser/dist/token-stream.js:352:12)
    at TokenStream.peek (/home/guido/gitrepos/LDS/node_modules/@salesforce-ux/scss-parser-aura/node_modules/scss-parser/dist/token-stream.js:248:26)
    at TokenStream.eof (/home/guido/gitrepos/LDS/node_modules/@salesforce-ux/scss-parser-aura/node_modules/scss-parser/dist/token-stream.js:282:26)
    at Object.eof (/home/guido/gitrepos/LDS/node_modules/@salesforce-ux/scss-parser-aura/node_modules/scss-parser/dist/token-stream.js:631:16)
    at Parser.parse_stylesheet (/home/guido/gitrepos/LDS/node_modules/@salesforce-ux/scss-parser-aura/node_modules/scss-parser/dist/parse.js:266:27)
    at module.exports (/home/guido/gitrepos/LDS/node_modules/@salesforce-ux/scss-parser-aura/node_modules/scss-parser/dist/parse.js:748:17)
    at Object.parse (/home/guido/gitrepos/LDS/node_modules/@salesforce-ux/scss-parser-aura/node_modules/scss-parser/dist/index.js:27:10)
    at runPlugins (/home/guido/gitrepos/LDS/node_modules/@salesforce-ux/scss-parser-aura/index.js:11:18)
    at module.exports.params (/home/guido/gitrepos/LDS/node_modules/@salesforce-ux/scss-parser-aura/index.js:49:23)
    at Task (/home/guido/gitrepos/LDS/scripts/compile/token-maps.js:271:20)
    at /home/guido/gitrepos/LDS/node_modules/data.task/lib/task.js:114:12
    at Task.fork (/home/guido/gitrepos/LDS/node_modules/data.task/lib/task.js:114:12)
    at _gulp2.default.task._gulp2.default.series.done (/home/guido/gitrepos/LDS/gulpfile.js:241:42)
[12:04:17] 'dist' errored after 44 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.8.3 gulp: `babel-node ./node_modules/gulp/bin/gulp.js "dist"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the design-system@2.8.3 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/guido/.npm/_logs/2019-03-09T11_04_17_967Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.8.3 dist: `npm run gulp -- dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the design-system@2.8.3 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/guido/.npm/_logs/2019-03-09T11_04_17_980Z-debug.log

**Comment by zahnster** [comment]
Hey @Luke1982, is this still an issue for you?

I was able to install Ubuntu 18.04 on a virtual machine and get the Design System project to run and build successfully. I did, however, have to use an older version of Node, as it seems that node-sass in particular only supports older versions of node on Linux.

I was successful with the following versions of node / npm:

Node: v8.16.0
NPM: v6.4.1

We will update our documentation to better state which versions of Node and NPM are supported.

If you are still encountering issues, please let us know which version of node / npm you are using. Be sure to reset package-lock.json if it is modified from the repository state.

**Comment by Luke1982** [comment]
Hi @zahnster, well it's been a while since I last tried. Let me check when I have some time and get back to you!

**Comment by megatimes** [comment]
@zahnster Confirmed that this solution worked for me on macOS after changing the Node version. 

Details: 
* Node v8.16.0 (nvm-managed)
* npm v6.4.1 (Brew-managed)
* macOS Mojave 10.14.5
