### ISSUE TITLE
Module Not Found Issue 

### ISSUE THREAD

**Issue by v22asthana** [salesforce-ux/design-system#739]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

> Are any specific browsers impacted by this bug?

> Which version of the Salesforce Lightning Design System are you using?

> What steps and/or code are needed to reproduce this issue?

> What did you expect to happen?

> What actually happened?

**Comment by v22asthana** [comment]
Not anle to run npm start getting error .
Error: Cannot find module 'D:\Salesforce_Front_End_Development\design-system\node_modules\gulp\bin\gulp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at Object.<anonymous> (C:\Users\abcd\AppData\Roaming\npm\node_modules\babel-cli\lib\_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@2.19.0 gulp: `babel-node ./node_modules/gulp/bin/gulp.js "build"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the design-system@2.19.0 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abcd\AppData\Roaming\npm-cache\_logs\2022-12-04T06_56_08_662Z-debug.log
npm ERR! code ELIFECYCLE

Please help me out

**Comment by Dottenpixel** [comment]
Hi @v22asthana, thanks for your can you update to node v14, and possibly 16, and see if the issue persists at those version levels? I'll look to fix that README mention of `v12` to be `v14`.
