### ISSUE TITLE
NPM Error

### ISSUE THREAD

**Issue by exitfish** [salesforce-ux/design-system#754]
> (REQUIRED) Include one or more screenshots if applicable, as well as a Codepen with the
reduced test case.

> Describe the issue. Is it a bug or a feature request (new component, new icon, new CSS class)?

After running `npm install && npm run build`, I am getting a slew of npm errors.

> Is this issue related to a specific component, variant, and/or state? If so, please detail which.

n/a

> Are any specific browsers impacted by this bug?

n/a

> Which version of the Salesforce Lightning Design System are you using?

2.20.1

> What steps and/or code are needed to reproduce this issue?

> What did you expect to happen?

Code to compile per the instructions.

> What actually happened?

npm failed at design-system@2.21.3 build script

the log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.14
3 info using node@v14.17.5
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle design-system@2.21.3~prebuild: design-system@2.21.3
6 info lifecycle design-system@2.21.3~build: design-system@2.21.3
7 verbose lifecycle design-system@2.21.3~build: unsafe-perm in lifecycle true
8 verbose lifecycle design-system@2.21.3~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/matthew/Documents/Breakline/Delaware/DE_DigiGov/design-system-main/node_modules/.bin:/Users/matthew/.npm-global/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/bin:/opt/homebrew/sbin
9 verbose lifecycle design-system@2.21.3~build: CWD: /Users/matthew/Documents/Breakline/Delaware/DE_DigiGov/design-system-main
10 silly lifecycle design-system@2.21.3~build: Args: [ '-c', 'npm run gulp -- build' ]
11 silly lifecycle design-system@2.21.3~build: Returned: code: 1  signal: null
12 info lifecycle design-system@2.21.3~build: Failed to exec build script
13 verbose stack Error: design-system@2.21.3 build: `npm run gulp -- build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid design-system@2.21.3
15 verbose cwd /Users/matthew/Documents/Breakline/Delaware/DE_DigiGov/design-system-main
16 verbose Darwin 22.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v14.17.5
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 1
22 error design-system@2.21.3 build: `npm run gulp -- build`
22 error Exit status 1
23 error Failed at the design-system@2.21.3 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Dottenpixel** [comment]
Thanks for your post @exitfish! Are you able to successfully install and build with more modern versions 2.21.5 or 2.22.0?

If not, what version of node/npm are you using?
